//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.27 at 03:54:43 PM MSK 
//


package org.example.filesFromXSD.registry;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.base.ListOptions;
import org.example.filesFromXSD.dictionary_v2.AnimalMarkingLocation;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.vetrf.ru/schema/cdm/base}listOptions" minOccurs="0"/>
 *         &lt;element ref="{http://api.vetrf.ru/schema/cdm/dictionary/v2}animalMarkingLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listOptions",
    "animalMarkingLocation"
})
@XmlRootElement(name = "getAnimalMarkingLocationListRequest")
public class GetAnimalMarkingLocationListRequest {

    @XmlElement(namespace = "http://api.vetrf.ru/schema/cdm/base")
    protected ListOptions listOptions;
    @XmlElement(namespace = "http://api.vetrf.ru/schema/cdm/dictionary/v2")
    protected AnimalMarkingLocation animalMarkingLocation;

    /**
     * Параметры запрашиваемого списка
     * 
     * @return
     *     possible object is
     *     {@link ListOptions }
     *     
     */
    public ListOptions getListOptions() {
        return listOptions;
    }

    /**
     * Sets the value of the listOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOptions }
     *     
     */
    public void setListOptions(ListOptions value) {
        this.listOptions = value;
    }

    /**
     * Параметры места нанесения средства маркирования для фильтрации
     * 
     * @return
     *     possible object is
     *     {@link AnimalMarkingLocation }
     *     
     */
    public AnimalMarkingLocation getAnimalMarkingLocation() {
        return animalMarkingLocation;
    }

    /**
     * Sets the value of the animalMarkingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalMarkingLocation }
     *     
     */
    public void setAnimalMarkingLocation(AnimalMarkingLocation value) {
        this.animalMarkingLocation = value;
    }

}
