//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.AnimalKeepingPurpose;
import org.example.filesFromXSD.dictionary_v2.SupervisedObject;


/**
 * �������� � ����������� ���������
 * 
 * <p>Java class for AnimalMovementEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnimalMovementEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}VeterinaryEvent">
 *       &lt;sequence>
 *         &lt;element name="consignor" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SupervisedObject" minOccurs="0"/>
 *         &lt;element name="consignee" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SupervisedObject" minOccurs="0"/>
 *         &lt;element name="transportInfo" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}TransportInfo" minOccurs="0"/>
 *         &lt;element name="shipmentRoute" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}ShipmentRoute" minOccurs="0"/>
 *         &lt;element name="purpose" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}AnimalKeepingPurpose" minOccurs="0"/>
 *         &lt;element name="associatedAnimalGroup" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}ObservableAnimalGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="associatedKeepingEvent" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalKeepingEvent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimalMovementEvent", propOrder = {
    "consignor",
    "consignee",
    "transportInfo",
    "shipmentRoute",
    "purpose",
    "associatedAnimalGroup",
    "associatedKeepingEvent"
})
public class AnimalMovementEvent
    extends VeterinaryEvent
{

    protected SupervisedObject consignor;
    protected SupervisedObject consignee;
    protected TransportInfo transportInfo;
    protected ShipmentRoute shipmentRoute;
    protected AnimalKeepingPurpose purpose;
    protected List<ObservableAnimalGroup> associatedAnimalGroup;
    protected List<AnimalKeepingEvent> associatedKeepingEvent;

    /**
     * Gets the value of the consignor property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisedObject }
     *     
     */
    public SupervisedObject getConsignor() {
        return consignor;
    }

    /**
     * Sets the value of the consignor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisedObject }
     *     
     */
    public void setConsignor(SupervisedObject value) {
        this.consignor = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisedObject }
     *     
     */
    public SupervisedObject getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisedObject }
     *     
     */
    public void setConsignee(SupervisedObject value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the transportInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransportInfo }
     *     
     */
    public TransportInfo getTransportInfo() {
        return transportInfo;
    }

    /**
     * Sets the value of the transportInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportInfo }
     *     
     */
    public void setTransportInfo(TransportInfo value) {
        this.transportInfo = value;
    }

    /**
     * Gets the value of the shipmentRoute property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentRoute }
     *     
     */
    public ShipmentRoute getShipmentRoute() {
        return shipmentRoute;
    }

    /**
     * Sets the value of the shipmentRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentRoute }
     *     
     */
    public void setShipmentRoute(ShipmentRoute value) {
        this.shipmentRoute = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalKeepingPurpose }
     *     
     */
    public AnimalKeepingPurpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalKeepingPurpose }
     *     
     */
    public void setPurpose(AnimalKeepingPurpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the associatedAnimalGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedAnimalGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedAnimalGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservableAnimalGroup }
     * 
     * 
     */
    public List<ObservableAnimalGroup> getAssociatedAnimalGroup() {
        if (associatedAnimalGroup == null) {
            associatedAnimalGroup = new ArrayList<ObservableAnimalGroup>();
        }
        return this.associatedAnimalGroup;
    }

    /**
     * Gets the value of the associatedKeepingEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedKeepingEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedKeepingEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimalKeepingEvent }
     * 
     * 
     */
    public List<AnimalKeepingEvent> getAssociatedKeepingEvent() {
        if (associatedKeepingEvent == null) {
            associatedKeepingEvent = new ArrayList<AnimalKeepingEvent>();
        }
        return this.associatedKeepingEvent;
    }

}
