//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * �������� � ��������, ������� ��������� � �.�.
 * 
 * <p>Java class for AnimalLifecycleEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnimalLifecycleEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}VeterinaryEvent">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="occurrenceReason" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalLifecycleEventReason" minOccurs="0"/>
 *           &lt;element name="associatedAnimalGroup" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}ObservableAnimalGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimalLifecycleEvent", propOrder = {
    "occurrenceReason",
    "associatedAnimalGroup"
})
public class AnimalLifecycleEvent
    extends VeterinaryEvent
{

    protected AnimalLifecycleEventReason occurrenceReason;
    protected List<ObservableAnimalGroup> associatedAnimalGroup;

    /**
     * Gets the value of the occurrenceReason property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalLifecycleEventReason }
     *     
     */
    public AnimalLifecycleEventReason getOccurrenceReason() {
        return occurrenceReason;
    }

    /**
     * Sets the value of the occurrenceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalLifecycleEventReason }
     *     
     */
    public void setOccurrenceReason(AnimalLifecycleEventReason value) {
        this.occurrenceReason = value;
    }

    /**
     * Gets the value of the associatedAnimalGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedAnimalGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedAnimalGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservableAnimalGroup }
     * 
     * 
     */
    public List<ObservableAnimalGroup> getAssociatedAnimalGroup() {
        if (associatedAnimalGroup == null) {
            associatedAnimalGroup = new ArrayList<ObservableAnimalGroup>();
        }
        return this.associatedAnimalGroup;
    }

}
