//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.base.ComplexDatePeriod;
import org.example.filesFromXSD.dictionary_v2.Country;


/**
 * �������� � ����� ��������� (������ ��������) � ��
 * 
 * <p>Java class for AnimalImportDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnimalImportDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="importDate" type="{http://api.vetrf.ru/schema/cdm/base}ComplexDatePeriod" minOccurs="0"/>
 *         &lt;element name="importCountry" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Country" minOccurs="0"/>
 *         &lt;element name="referencedMovementEvent" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalMovementEvent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimalImportDetails", propOrder = {
    "importDate",
    "importCountry",
    "referencedMovementEvent"
})
public class AnimalImportDetails {

    protected ComplexDatePeriod importDate;
    protected Country importCountry;
    protected List<AnimalMovementEvent> referencedMovementEvent;

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexDatePeriod }
     *     
     */
    public ComplexDatePeriod getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexDatePeriod }
     *     
     */
    public void setImportDate(ComplexDatePeriod value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the importCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getImportCountry() {
        return importCountry;
    }

    /**
     * Sets the value of the importCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setImportCountry(Country value) {
        this.importCountry = value;
    }

    /**
     * Gets the value of the referencedMovementEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencedMovementEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencedMovementEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimalMovementEvent }
     * 
     * 
     */
    public List<AnimalMovementEvent> getReferencedMovementEvent() {
        if (referencedMovementEvent == null) {
            referencedMovementEvent = new ArrayList<AnimalMovementEvent>();
        }
        return this.referencedMovementEvent;
    }

}
