//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.Measure;


/**
 * ����������� �������.
 * 
 * <p>Java class for ControlSample complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlSample">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="affixedSeal" type="{http://api.vetrf.ru/schema/cdm/base}String255" minOccurs="0"/>
 *         &lt;element name="controlSampleVolume" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Measure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlSample", propOrder = {
    "affixedSeal",
    "controlSampleVolume"
})
public class ControlSample {

    protected String affixedSeal;
    protected Measure controlSampleVolume;

    /**
     * Gets the value of the affixedSeal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffixedSeal() {
        return affixedSeal;
    }

    /**
     * Sets the value of the affixedSeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffixedSeal(String value) {
        this.affixedSeal = value;
    }

    /**
     * Gets the value of the controlSampleVolume property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getControlSampleVolume() {
        return controlSampleVolume;
    }

    /**
     * Sets the value of the controlSampleVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setControlSampleVolume(Measure value) {
        this.controlSampleVolume = value;
    }

}
