//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.ControlSampleIndicator;
import org.example.filesFromXSD.dictionary_v2.SampleReturnType;


/**
 * �������� � ����������� ��������.
 * 
 * <p>Java class for ControlSampleDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlSampleDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controlSamplePresence" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}ControlSampleIndicator" minOccurs="0"/>
 *         &lt;element name="controlSampleCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="controlSampleReturning" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SampleReturnType" minOccurs="0"/>
 *         &lt;element name="controlSampleList" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}ControlSampleList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlSampleDetails", propOrder = {
    "controlSamplePresence",
    "controlSampleCount",
    "controlSampleReturning",
    "controlSampleList"
})
public class ControlSampleDetails {

    protected ControlSampleIndicator controlSamplePresence;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger controlSampleCount;
    protected SampleReturnType controlSampleReturning;
    protected ControlSampleList controlSampleList;

    /**
     * Gets the value of the controlSamplePresence property.
     * 
     * @return
     *     possible object is
     *     {@link ControlSampleIndicator }
     *     
     */
    public ControlSampleIndicator getControlSamplePresence() {
        return controlSamplePresence;
    }

    /**
     * Sets the value of the controlSamplePresence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlSampleIndicator }
     *     
     */
    public void setControlSamplePresence(ControlSampleIndicator value) {
        this.controlSamplePresence = value;
    }

    /**
     * Gets the value of the controlSampleCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getControlSampleCount() {
        return controlSampleCount;
    }

    /**
     * Sets the value of the controlSampleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setControlSampleCount(BigInteger value) {
        this.controlSampleCount = value;
    }

    /**
     * Gets the value of the controlSampleReturning property.
     * 
     * @return
     *     possible object is
     *     {@link SampleReturnType }
     *     
     */
    public SampleReturnType getControlSampleReturning() {
        return controlSampleReturning;
    }

    /**
     * Sets the value of the controlSampleReturning property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleReturnType }
     *     
     */
    public void setControlSampleReturning(SampleReturnType value) {
        this.controlSampleReturning = value;
    }

    /**
     * Gets the value of the controlSampleList property.
     * 
     * @return
     *     possible object is
     *     {@link ControlSampleList }
     *     
     */
    public ControlSampleList getControlSampleList() {
        return controlSampleList;
    }

    /**
     * Sets the value of the controlSampleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlSampleList }
     *     
     */
    public void setControlSampleList(ControlSampleList value) {
        this.controlSampleList = value;
    }

}
