//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.base.GenericVersioningEntity;
import org.example.filesFromXSD.dictionary_v2.FMPRegistryProduct;

/**
 * ���, ����������� ������ ������� ��, ��, �� ��� ����.
 * 
 * <p>Java class for FMPRegistryEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FMPRegistryEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/base}GenericVersioningEntity">
 *       &lt;sequence>
 *         &lt;element name="registryStatus" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}FMPRegistryStatus" minOccurs="0"/>
 *         &lt;element name="fmpProduct" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}FMPRegistryProduct" minOccurs="0"/>
 *         &lt;element name="registrationCertificate" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}RegistrationCertificate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FMPRegistryEntry", propOrder = {
    "registryStatus",
    "fmpProduct",
    "registrationCertificate"
})
public class FMPRegistryEntry
    extends GenericVersioningEntity
{

    protected FMPRegistryStatus registryStatus;
    protected FMPRegistryProduct fmpProduct;
    protected RegistrationCertificate registrationCertificate;

    /**
     * Gets the value of the registryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link FMPRegistryStatus }
     *     
     */
    public FMPRegistryStatus getRegistryStatus() {
        return registryStatus;
    }

    /**
     * Sets the value of the registryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FMPRegistryStatus }
     *     
     */
    public void setRegistryStatus(FMPRegistryStatus value) {
        this.registryStatus = value;
    }

    /**
     * Gets the value of the fmpProduct property.
     * 
     * @return
     *     possible object is
     *     {@link FMPRegistryProduct }
     *     
     */
    public FMPRegistryProduct getFmpProduct() {
        return fmpProduct;
    }

    /**
     * Sets the value of the fmpProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link FMPRegistryProduct }
     *     
     */
    public void setFmpProduct(FMPRegistryProduct value) {
        this.fmpProduct = value;
    }

    /**
     * Gets the value of the registrationCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationCertificate }
     *     
     */
    public RegistrationCertificate getRegistrationCertificate() {
        return registrationCertificate;
    }

    /**
     * Sets the value of the registrationCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationCertificate }
     *     
     */
    public void setRegistrationCertificate(RegistrationCertificate value) {
        this.registrationCertificate = value;
    }

}
