//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.LabSampleMaterial;



/**
 * �������� � �����, ���������� ��� ���������� ������������ ���������.
 * 
 * <p>Java class for LaboratoryResearchSample complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LaboratoryResearchSample">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="material" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}LabSampleMaterial" minOccurs="0"/>
 *         &lt;element name="specifiedMaterialName" type="{http://api.vetrf.ru/schema/cdm/base}String255" minOccurs="0"/>
 *         &lt;element name="laboratoryResearch" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}LaboratoryResearchEvent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="conclusion" type="{http://api.vetrf.ru/schema/cdm/base}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LaboratoryResearchSample", propOrder = {
    "material",
    "specifiedMaterialName",
    "laboratoryResearch",
    "conclusion"
})
public class LaboratoryResearchSample {

    protected LabSampleMaterial material;
    protected String specifiedMaterialName;
    protected List<LaboratoryResearchEvent> laboratoryResearch;
    protected String conclusion;

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link LabSampleMaterial }
     *     
     */
    public LabSampleMaterial getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabSampleMaterial }
     *     
     */
    public void setMaterial(LabSampleMaterial value) {
        this.material = value;
    }

    /**
     * Gets the value of the specifiedMaterialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifiedMaterialName() {
        return specifiedMaterialName;
    }

    /**
     * Sets the value of the specifiedMaterialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifiedMaterialName(String value) {
        this.specifiedMaterialName = value;
    }

    /**
     * Gets the value of the laboratoryResearch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the laboratoryResearch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaboratoryResearch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LaboratoryResearchEvent }
     * 
     * 
     */
    public List<LaboratoryResearchEvent> getLaboratoryResearch() {
        if (laboratoryResearch == null) {
            laboratoryResearch = new ArrayList<LaboratoryResearchEvent>();
        }
        return this.laboratoryResearch;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConclusion(String value) {
        this.conclusion = value;
    }

}
