//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.*;




/**
 * ���������� ���� �� ��������������� ����� ������� �� �������������� ���������.
 *          
 * 
 * <p>Java class for VeterinaryPermit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VeterinaryPermit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}Document">
 *       &lt;sequence>
 *         &lt;element name="permitYear" type="{http://api.vetrf.ru/schema/cdm/base}Year" minOccurs="0"/>
 *         &lt;element name="permitDecision" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}PermitDecision" minOccurs="0"/>
 *         &lt;element name="centralDepartment" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Organization" minOccurs="0"/>
 *         &lt;element name="vetDepartment" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Organization" minOccurs="0"/>
 *         &lt;element name="signedBy" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}User" minOccurs="0"/>
 *         &lt;element name="general" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="transferType" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}TransferType" minOccurs="0"/>
 *         &lt;element name="productType" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}ProductType" minOccurs="0"/>
 *         &lt;element name="transferPurpose" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Purpose" minOccurs="0"/>
 *         &lt;element name="businessEntity" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}BusinessEntity" minOccurs="0"/>
 *         &lt;element name="originCountry" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Country" minOccurs="0"/>
 *         &lt;element name="importCountry" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Country" minOccurs="0"/>
 *         &lt;element name="exportCountry" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Country" minOccurs="0"/>
 *         &lt;element name="supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="consignee" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}BusinessEntity" minOccurs="0"/>
 *         &lt;element name="transferFor" type="{http://api.vetrf.ru/schema/cdm/base}String255" minOccurs="0"/>
 *         &lt;element name="transferVia" type="{http://api.vetrf.ru/schema/cdm/base}String255" minOccurs="0"/>
 *         &lt;element name="customsClearanceRegion" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Region" minOccurs="0"/>
 *         &lt;element name="storagePoint" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}StoragePoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="shipmentPoint" type="{http://api.vetrf.ru/schema/cdm/base}String255" minOccurs="0"/>
 *         &lt;element name="bipListRestricted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="borderInspectionPointList" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}BorderVetControlPostList" minOccurs="0"/>
 *         &lt;element name="transportTypeList" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}TransportTypeList" minOccurs="0"/>
 *         &lt;element name="cargoList" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}VetPermitCargoItemList" minOccurs="0"/>
 *         &lt;element name="conditionList" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}TransferConditionList" minOccurs="0"/>
 *         &lt;element name="additionalConditionList" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}TransferConditionList" minOccurs="0"/>
 *         &lt;element name="additionalInfo" type="{http://api.vetrf.ru/schema/cdm/base}Text" minOccurs="0"/>
 *         &lt;element name="conclusion" type="{http://api.vetrf.ru/schema/cdm/base}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VeterinaryPermit", propOrder = {
    "permitYear",
    "permitDecision",
    "centralDepartment",
    "vetDepartment",
    "signedBy",
    "general",
    "transferType",
    "productType",
    "transferPurpose",
    "businessEntity",
    "originCountry",
    "importCountry",
    "exportCountry",
    "supplier",
    "consignee",
    "transferFor",
    "transferVia",
    "customsClearanceRegion",
    "storagePoint",
    "shipmentPoint",
    "bipListRestricted",
    "borderInspectionPointList",
    "transportTypeList",
    "cargoList",
    "conditionList",
    "additionalConditionList",
    "additionalInfo",
    "conclusion"
})
public class VeterinaryPermit
    extends Document
{

    protected Integer permitYear;
    protected PermitDecision permitDecision;
    protected Organization centralDepartment;
    protected Organization vetDepartment;
    protected User signedBy;
    protected Boolean general;
    protected TransferType transferType;
    protected ProductType productType;
    protected Purpose transferPurpose;
    protected BusinessEntity businessEntity;
    protected Country originCountry;
    protected Country importCountry;
    protected Country exportCountry;
    protected String supplier;
    protected BusinessEntity consignee;
    protected String transferFor;
    protected String transferVia;
    protected Region customsClearanceRegion;
    protected List<StoragePoint> storagePoint;
    protected String shipmentPoint;
    protected Boolean bipListRestricted;
    protected BorderVetControlPostList borderInspectionPointList;
    protected TransportTypeList transportTypeList;
    protected VetPermitCargoItemList cargoList;
    protected TransferConditionList conditionList;
    protected TransferConditionList additionalConditionList;
    protected String additionalInfo;
    protected String conclusion;

    /**
     * Gets the value of the permitYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPermitYear() {
        return permitYear;
    }

    /**
     * Sets the value of the permitYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPermitYear(Integer value) {
        this.permitYear = value;
    }

    /**
     * Gets the value of the permitDecision property.
     * 
     * @return
     *     possible object is
     *     {@link PermitDecision }
     *     
     */
    public PermitDecision getPermitDecision() {
        return permitDecision;
    }

    /**
     * Sets the value of the permitDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermitDecision }
     *     
     */
    public void setPermitDecision(PermitDecision value) {
        this.permitDecision = value;
    }

    /**
     * Gets the value of the centralDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getCentralDepartment() {
        return centralDepartment;
    }

    /**
     * Sets the value of the centralDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setCentralDepartment(Organization value) {
        this.centralDepartment = value;
    }

    /**
     * Gets the value of the vetDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getVetDepartment() {
        return vetDepartment;
    }

    /**
     * Sets the value of the vetDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setVetDepartment(Organization value) {
        this.vetDepartment = value;
    }

    /**
     * Gets the value of the signedBy property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getSignedBy() {
        return signedBy;
    }

    /**
     * Sets the value of the signedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setSignedBy(User value) {
        this.signedBy = value;
    }

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGeneral(Boolean value) {
        this.general = value;
    }

    /**
     * Gets the value of the transferType property.
     * 
     * @return
     *     possible object is
     *     {@link TransferType }
     *     
     */
    public TransferType getTransferType() {
        return transferType;
    }

    /**
     * Sets the value of the transferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferType }
     *     
     */
    public void setTransferType(TransferType value) {
        this.transferType = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProductType(ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the transferPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose }
     *     
     */
    public Purpose getTransferPurpose() {
        return transferPurpose;
    }

    /**
     * Sets the value of the transferPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose }
     *     
     */
    public void setTransferPurpose(Purpose value) {
        this.transferPurpose = value;
    }

    /**
     * Gets the value of the businessEntity property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEntity }
     *     
     */
    public BusinessEntity getBusinessEntity() {
        return businessEntity;
    }

    /**
     * Sets the value of the businessEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEntity }
     *     
     */
    public void setBusinessEntity(BusinessEntity value) {
        this.businessEntity = value;
    }

    /**
     * Gets the value of the originCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getOriginCountry() {
        return originCountry;
    }

    /**
     * Sets the value of the originCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setOriginCountry(Country value) {
        this.originCountry = value;
    }

    /**
     * Gets the value of the importCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getImportCountry() {
        return importCountry;
    }

    /**
     * Sets the value of the importCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setImportCountry(Country value) {
        this.importCountry = value;
    }

    /**
     * Gets the value of the exportCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getExportCountry() {
        return exportCountry;
    }

    /**
     * Sets the value of the exportCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setExportCountry(Country value) {
        this.exportCountry = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEntity }
     *     
     */
    public BusinessEntity getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEntity }
     *     
     */
    public void setConsignee(BusinessEntity value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the transferFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferFor() {
        return transferFor;
    }

    /**
     * Sets the value of the transferFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferFor(String value) {
        this.transferFor = value;
    }

    /**
     * Gets the value of the transferVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferVia() {
        return transferVia;
    }

    /**
     * Sets the value of the transferVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferVia(String value) {
        this.transferVia = value;
    }

    /**
     * Gets the value of the customsClearanceRegion property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public Region getCustomsClearanceRegion() {
        return customsClearanceRegion;
    }

    /**
     * Sets the value of the customsClearanceRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setCustomsClearanceRegion(Region value) {
        this.customsClearanceRegion = value;
    }

    /**
     * Gets the value of the storagePoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storagePoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoragePoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StoragePoint }
     * 
     * 
     */
    public List<StoragePoint> getStoragePoint() {
        if (storagePoint == null) {
            storagePoint = new ArrayList<StoragePoint>();
        }
        return this.storagePoint;
    }

    /**
     * Gets the value of the shipmentPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentPoint() {
        return shipmentPoint;
    }

    /**
     * Sets the value of the shipmentPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentPoint(String value) {
        this.shipmentPoint = value;
    }

    /**
     * Gets the value of the bipListRestricted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBipListRestricted() {
        return bipListRestricted;
    }

    /**
     * Sets the value of the bipListRestricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBipListRestricted(Boolean value) {
        this.bipListRestricted = value;
    }

    /**
     * Gets the value of the borderInspectionPointList property.
     * 
     * @return
     *     possible object is
     *     {@link BorderVetControlPostList }
     *     
     */
    public BorderVetControlPostList getBorderInspectionPointList() {
        return borderInspectionPointList;
    }

    /**
     * Sets the value of the borderInspectionPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BorderVetControlPostList }
     *     
     */
    public void setBorderInspectionPointList(BorderVetControlPostList value) {
        this.borderInspectionPointList = value;
    }

    /**
     * Gets the value of the transportTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link TransportTypeList }
     *     
     */
    public TransportTypeList getTransportTypeList() {
        return transportTypeList;
    }

    /**
     * Sets the value of the transportTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportTypeList }
     *     
     */
    public void setTransportTypeList(TransportTypeList value) {
        this.transportTypeList = value;
    }

    /**
     * Gets the value of the cargoList property.
     * 
     * @return
     *     possible object is
     *     {@link VetPermitCargoItemList }
     *     
     */
    public VetPermitCargoItemList getCargoList() {
        return cargoList;
    }

    /**
     * Sets the value of the cargoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VetPermitCargoItemList }
     *     
     */
    public void setCargoList(VetPermitCargoItemList value) {
        this.cargoList = value;
    }

    /**
     * Gets the value of the conditionList property.
     * 
     * @return
     *     possible object is
     *     {@link TransferConditionList }
     *     
     */
    public TransferConditionList getConditionList() {
        return conditionList;
    }

    /**
     * Sets the value of the conditionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferConditionList }
     *     
     */
    public void setConditionList(TransferConditionList value) {
        this.conditionList = value;
    }

    /**
     * Gets the value of the additionalConditionList property.
     * 
     * @return
     *     possible object is
     *     {@link TransferConditionList }
     *     
     */
    public TransferConditionList getAdditionalConditionList() {
        return additionalConditionList;
    }

    /**
     * Sets the value of the additionalConditionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferConditionList }
     *     
     */
    public void setAdditionalConditionList(TransferConditionList value) {
        this.additionalConditionList = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConclusion(String value) {
        this.conclusion = value;
    }

}
