//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.mercury_vet_document;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.BusinessEntity;
import org.example.filesFromXSD.dictionary_v2.Country;


/**
 * 
 *             ���������� � ������������ ������ ��� ����������� ������-���������.
 *          
 * 
 * <p>Java class for WBRComplianceStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WBRComplianceStatement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}Document">
 *       &lt;sequence>
 *         &lt;element name="decision" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}WBRComplianceDecision"/>
 *         &lt;element name="conclusion" type="{http://api.vetrf.ru/schema/cdm/base}Text" minOccurs="0"/>
 *         &lt;element name="importCountry" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Country"/>
 *         &lt;element name="consignor" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}BusinessEntity"/>
 *         &lt;element name="consignee" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}BusinessEntity"/>
 *         &lt;element name="officialVeterinarian" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}User" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WBRComplianceStatement", propOrder = {
    "decision",
    "conclusion",
    "importCountry",
    "consignor",
    "consignee",
    "officialVeterinarian"
})
public class WBRComplianceStatement
    extends Document
{

    @XmlElement(required = true)
    protected WBRComplianceDecision decision;
    protected String conclusion;
    @XmlElement(required = true)
    protected Country importCountry;
    @XmlElement(required = true)
    protected BusinessEntity consignor;
    @XmlElement(required = true)
    protected BusinessEntity consignee;
    protected User officialVeterinarian;

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link WBRComplianceDecision }
     *     
     */
    public WBRComplianceDecision getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link WBRComplianceDecision }
     *     
     */
    public void setDecision(WBRComplianceDecision value) {
        this.decision = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConclusion(String value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the importCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getImportCountry() {
        return importCountry;
    }

    /**
     * Sets the value of the importCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setImportCountry(Country value) {
        this.importCountry = value;
    }

    /**
     * Gets the value of the consignor property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEntity }
     *     
     */
    public BusinessEntity getConsignor() {
        return consignor;
    }

    /**
     * Sets the value of the consignor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEntity }
     *     
     */
    public void setConsignor(BusinessEntity value) {
        this.consignor = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEntity }
     *     
     */
    public BusinessEntity getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEntity }
     *     
     */
    public void setConsignee(BusinessEntity value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the officialVeterinarian property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getOfficialVeterinarian() {
        return officialVeterinarian;
    }

    /**
     * Sets the value of the officialVeterinarian property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setOfficialVeterinarian(User value) {
        this.officialVeterinarian = value;
    }

}
