//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.02 at 04:09:00 PM MSK 
//


package org.example.filesFromXSD.herriot_applications_v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 �����: ���������� �������� �� ������
 *             
 * 
 * <p>Java class for ExcludeFromAnimalGroupResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcludeFromAnimalGroupResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/application}ApplicationResultData">
 *       &lt;sequence>
 *         &lt;element name="animalRegistration" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalRegistration" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcludeFromAnimalGroupResponse", propOrder = {
    "animalRegistration"
})
public class ExcludeFromAnimalGroupResponse
    extends ApplicationResultData
{

    protected AnimalRegistration animalRegistration;

    /**
     * Gets the value of the animalRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalRegistration }
     *     
     */
    public AnimalRegistration getAnimalRegistration() {
        return animalRegistration;
    }

    /**
     * Sets the value of the animalRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalRegistration }
     *     
     */
    public void setAnimalRegistration(AnimalRegistration value) {
        this.animalRegistration = value;
    }

}
