//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.02 at 04:09:00 PM MSK 
//


package org.example.filesFromXSD.herriot_applications_v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.mercury_vet_document.AnimalMedicationEvent;


/**
 * 
 *                 �����: ��������� �������� (������) ��������
 *                 � ������������������ ������������ ���������������� ����������� �� �������������� ������
 *             
 * 
 * <p>Java class for GetAnimalVeterinaryEventByUuidResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetAnimalVeterinaryEventByUuidResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/application}ApplicationResultData">
 *       &lt;sequence>
 *         &lt;element name="medicationEvent" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalMedicationEvent" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAnimalVeterinaryEventByUuidResponse", propOrder = {
    "medicationEvent"
})
public class GetAnimalVeterinaryEventByUuidResponse
    extends ApplicationResultData
{

    protected AnimalMedicationEvent medicationEvent;

    /**
     * Gets the value of the medicationEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalMedicationEvent }
     *     
     */
    public AnimalMedicationEvent getMedicationEvent() {
        return medicationEvent;
    }

    /**
     * Sets the value of the medicationEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalMedicationEvent }
     *     
     */
    public void setMedicationEvent(AnimalMedicationEvent value) {
        this.medicationEvent = value;
    }

}
