//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.02 at 04:09:00 PM MSK 
//


package org.example.filesFromXSD.herriot_applications_v1;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.*;
import org.example.filesFromXSD.base.DateInterval;
import org.example.filesFromXSD.base.ListOptions;
import org.example.filesFromXSD.dictionary_v2.AnimalSpecies;
import org.example.filesFromXSD.dictionary_v2.Location;
import org.example.filesFromXSD.dictionary_v2.Region;
import org.example.filesFromXSD.dictionary_v2.SupervisedObject;


/**
 * 
 *                 ������: ��������� ������ ��������� �� �������� ���������
 *                 � ����������� ��������� ��� ������ �������� �� ��������� ������ �������
 *             
 * 
 * <p>Java class for GetAnimalRegistrationChangesListRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetAnimalRegistrationChangesListRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/herriot/applications/v1}HerriotApplicationRequest">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.vetrf.ru/schema/cdm/base}listOptions" minOccurs="0"/>
 *         &lt;element ref="{http://api.vetrf.ru/schema/cdm/base}updateDateInterval" minOccurs="0"/>
 *         &lt;element name="region" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Region"/>
 *         &lt;element name="location" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="operator" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SupervisedObject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="animalSpecies" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}AnimalSpecies" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAnimalRegistrationChangesListRequest", propOrder = {
    "listOptions",
    "updateDateInterval",
    "region",
    "location",
    "operator",
    "animalSpecies"
})
public class GetAnimalRegistrationChangesListRequest
    extends HerriotApplicationRequest
{

    @XmlElement(namespace = "http://api.vetrf.ru/schema/cdm/base")
    protected ListOptions listOptions;
    @XmlElement(namespace = "http://api.vetrf.ru/schema/cdm/base")
    protected DateInterval updateDateInterval;
    @XmlElement(required = true)
    protected Region region;
    protected List<Location> location;
    protected List<SupervisedObject> operator;
    protected List<AnimalSpecies> animalSpecies;

    /**
     * ��������� �������������� ������
     * 
     * @return
     *     possible object is
     *     {@link ListOptions }
     *     
     */
    public ListOptions getListOptions() {
        return listOptions;
    }

    /**
     * Sets the value of the listOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOptions }
     *     
     */
    public void setListOptions(ListOptions value) {
        this.listOptions = value;
    }

    /**
     * �������� ������� ����������
     * 
     * @return
     *     possible object is
     *     {@link DateInterval }
     *     
     */
    public DateInterval getUpdateDateInterval() {
        return updateDateInterval;
    }

    /**
     * Sets the value of the updateDateInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateInterval }
     *     
     */
    public void setUpdateDateInterval(DateInterval value) {
        this.updateDateInterval = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public Region getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setRegion(Region value) {
        this.region = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     */
    public List<Location> getLocation() {
        if (location == null) {
            location = new ArrayList<Location>();
        }
        return this.location;
    }

    /**
     * Gets the value of the operator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupervisedObject }
     * 
     * 
     */
    public List<SupervisedObject> getOperator() {
        if (operator == null) {
            operator = new ArrayList<SupervisedObject>();
        }
        return this.operator;
    }

    public void addOperator(SupervisedObject op) {
        if (operator == null) {
            operator = new ArrayList<SupervisedObject>();
        }
        operator.add(op);
    }

    /**
     * Gets the value of the animalSpecies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animalSpecies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimalSpecies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnimalSpecies }
     * 
     * 
     */
    public List<AnimalSpecies> getAnimalSpecies() {
        if (animalSpecies == null) {
            animalSpecies = new ArrayList<AnimalSpecies>();
        }
        return this.animalSpecies;
    }
    public void addAnimalSpecies(AnimalSpecies species){
        if (animalSpecies == null) {
            animalSpecies = new ArrayList<AnimalSpecies>();
        }
        animalSpecies.add(species);
    }

}
