//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.02 at 04:09:00 PM MSK 
//


package org.example.filesFromXSD.herriot_applications_v1;

import jakarta.xml.bind.annotation.*;
import org.example.filesFromXSD.mercury_vet_document.AnimalMovementEvent;
import org.example.filesFromXSD.mercury_vet_document.AnimalRegistrationList;


/**
 * 
 *                 ������: ����������� �������� � ����������� / ����� ������������ ������������������� ��������� ��� ����� ��������
 *             
 * 
 * <p>Java class for RegisterAnimalMovementEventRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterAnimalMovementEventRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/herriot/applications/v1}HerriotApplicationRequest">
 *       &lt;sequence>
 *         &lt;element name="referencedMovementEvent" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalMovementEvent"/>
 *         &lt;element name="movementAnimalRegistrationList" type="{http://api.vetrf.ru/schema/cdm/mercury/vet-document/v2}AnimalRegistrationList"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterAnimalMovementEventRequest", propOrder = {
    "referencedMovementEvent",
    "movementAnimalRegistrationList"
})
public class RegisterAnimalMovementEventRequest
    extends HerriotApplicationRequest
{

    @XmlElement(required = true)
    protected AnimalMovementEvent referencedMovementEvent;
    @XmlElement(required = true)
    protected AnimalRegistrationList movementAnimalRegistrationList;

    /**
     * Gets the value of the referencedMovementEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalMovementEvent }
     *     
     */
    public AnimalMovementEvent getReferencedMovementEvent() {
        return referencedMovementEvent;
    }

    /**
     * Sets the value of the referencedMovementEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalMovementEvent }
     *     
     */
    public void setReferencedMovementEvent(AnimalMovementEvent value) {
        this.referencedMovementEvent = value;
    }

    /**
     * Gets the value of the movementAnimalRegistrationList property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalRegistrationList }
     *     
     */
    public AnimalRegistrationList getMovementAnimalRegistrationList() {
        return movementAnimalRegistrationList;
    }

    /**
     * Sets the value of the movementAnimalRegistrationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalRegistrationList }
     *     
     */
    public void setMovementAnimalRegistrationList(AnimalRegistrationList value) {
        this.movementAnimalRegistrationList = value;
    }

}
