//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.02 at 04:09:00 PM MSK 
//


package org.example.filesFromXSD.herriot_applications_v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.example.filesFromXSD.dictionary_v2.UnifiedAnimalIDList;


/**
 * 
 *                 �����: �������� �������� ���� (���������� ������� ������� ������������)
 *             
 * 
 * <p>Java class for VerifyAnimalIDResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerifyAnimalIDResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.vetrf.ru/schema/cdm/application}ApplicationResultData">
 *       &lt;sequence>
 *         &lt;element name="animalIDList" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}UnifiedAnimalIDList"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerifyAnimalIDResponse", propOrder = {
    "animalIDList"
})
public class VerifyAnimalIDResponse
    extends ApplicationResultData
{

    @XmlElement(required = true)
    protected UnifiedAnimalIDList animalIDList;

    /**
     * Gets the value of the animalIDList property.
     * 
     * @return
     *     possible object is
     *     {@link UnifiedAnimalIDList }
     *     
     */
    public UnifiedAnimalIDList getAnimalIDList() {
        return animalIDList;
    }

    /**
     * Sets the value of the animalIDList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnifiedAnimalIDList }
     *     
     */
    public void setAnimalIDList(UnifiedAnimalIDList value) {
        this.animalIDList = value;
    }

}
