//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.23 at 05:39:12 PM MSK 
//


package org.example.filesFromXSD.application;

import jakarta.xml.bind.annotation.*;
import org.example.filesFromXSD.application.ws_defenitions.ReceiveApplicationResultResponse;


/**
 * <p>Java class for ApplicationResultWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationResultWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="encoding" type="{http://api.vetrf.ru/schema/cdm/application}ContentEncoding" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlSeeAlso(
        ReceiveApplicationResultResponse.class
)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationResultWrapper", propOrder = {
    "any"
})
public class ApplicationResultWrapper {

    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute
    protected ContentEncoding encoding;

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link ContentEncoding }
     *     
     */
    public ContentEncoding getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentEncoding }
     *     
     */
    public void setEncoding(ContentEncoding value) {
        this.encoding = value;
    }

}
