//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.23 at 05:39:12 PM MSK 
//


package org.example.filesFromXSD.application;

import jakarta.xml.bind.annotation.*;
import org.example.filesFromXSD.base.GenericVersioningEntity;
import org.example.filesFromXSD.dictionary_v2.*;
import org.example.filesFromXSD.herriot_applications_v1.AnimalRegistration;
import org.example.filesFromXSD.herriot_applications_v1.RegisterAnimalRequest;
import org.example.filesFromXSD.mercury_vet_document.Document;
import org.example.filesFromXSD.mercury_vet_document.ShipmentRoutePoint;
import org.example.filesFromXSD.mercury_vet_document.User;
import org.example.filesFromXSD.mercury_vet_document.VetPermitCargoItem;


/**
 * <p>Java class for ApplicationDataWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationDataWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="encoding" type="{http://api.vetrf.ru/schema/cdm/application}ContentEncoding" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationDataWrapper", propOrder = {
    "data"
})
@XmlSeeAlso({
        AnimalRegistration.class,
        RegisterAnimalRequest.class
})
public class ApplicationDataWrapper {

    @XmlAnyElement(lax = true)
    protected Object data;
    @XmlAttribute
    protected ContentEncoding encoding;

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getData() {
        return data;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setData(Object value) {
        this.data = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link ContentEncoding }
     *     
     */
    public ContentEncoding getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentEncoding }
     *     
     */
    public void setEncoding(ContentEncoding value) {
        this.encoding = value;
    }

}
