//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.23 at 05:39:12 PM MSK 
//


package org.example.filesFromXSD.application;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentEncoding.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContentEncoding">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="plain"/>
 *     &lt;enumeration value="gzip"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContentEncoding")
@XmlEnum
public enum ContentEncoding {

    @XmlEnumValue("plain")
    PLAIN("plain"),
    @XmlEnumValue("gzip")
    GZIP("gzip");
    private final String value;

    ContentEncoding(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContentEncoding fromValue(String v) {
        for (ContentEncoding c: ContentEncoding.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
