//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.codelist;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonFoodProductSourceTypeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NonFoodProductSourceTypeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CATTLE_SLAUGHTER"/>
 *     &lt;enumeration value="LOSS_OF_CATTLE"/>
 *     &lt;enumeration value="MANUFACTURED"/>
 *     &lt;enumeration value="MIXED"/>
 *     &lt;enumeration value="FROM_HEALTHY_ANIMALS"/>
 *     &lt;enumeration value="FROM_SICK_ANIMALS"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NonFoodProductSourceTypeContentType", namespace = "http://api.vetrf.ru/schema/cdm/codelist/v2")
@XmlEnum
public enum NonFoodProductSourceTypeContentType {


    /**
     * ��������.
     * 
     */
    CATTLE_SLAUGHTER,

    /**
     * �����.
     * 
     */
    LOSS_OF_CATTLE,

    /**
     * ������������.
     * 
     */
    MANUFACTURED,

    /**
     * �������.
     * 
     */
    MIXED,

    /**
     * ���������� �� �������� ��������.
     * 
     */
    FROM_HEALTHY_ANIMALS,

    /**
     * ���������� �� ������� ��������.
     * 
     */
    FROM_SICK_ANIMALS,

    /**
     * ����������� ���
     * 
     */
    UNKNOWN,

    /**
     * �� ����������/������
     * 
     */
    UNDEFINED;

    public String value() {
        return name();
    }

    public static NonFoodProductSourceTypeContentType fromValue(String v) {
        return valueOf(v);
    }

}
