//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.dictionary_v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * �������� � ����� ��������/���������� ���������
 * 
 * <p>Java class for AnimalKeepingLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnimalKeepingLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}Location" minOccurs="0"/>
 *         &lt;element name="supervisedObject" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SupervisedObject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimalKeepingLocation", propOrder = {
    "location",
    "supervisedObject"
})
public class AnimalKeepingLocation {

    protected Location location;
    protected SupervisedObject supervisedObject;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the supervisedObject property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisedObject }
     *     
     */
    public SupervisedObject getSupervisedObject() {
        return supervisedObject;
    }

    /**
     * Sets the value of the supervisedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisedObject }
     *     
     */
    public void setSupervisedObject(SupervisedObject value) {
        this.supervisedObject = value;
    }

}
