//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.dictionary_v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * �������� � �������� ������������
 * 
 * <p>Java class for AnimalMarkingMeans complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnimalMarkingMeans">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}AnimalMarkingMeansType" minOccurs="0"/>
 *         &lt;element name="producer" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}SupervisedObject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimalMarkingMeans", propOrder = {
    "type",
    "producer"
})
public class AnimalMarkingMeans {

    protected AnimalMarkingMeansType type;
    protected SupervisedObject producer;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AnimalMarkingMeansType }
     *     
     */
    public AnimalMarkingMeansType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimalMarkingMeansType }
     *     
     */
    public void setType(AnimalMarkingMeansType value) {
        this.type = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisedObject }
     *     
     */
    public SupervisedObject getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisedObject }
     *     
     */
    public void setProducer(SupervisedObject value) {
        this.producer = value;
    }

}
