//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.dictionary_v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalStatusTypeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ApprovalStatusTypeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *     &lt;enumeration value="WITHOUT_RESTRICTION"/>
 *     &lt;enumeration value="ENHANCED_MONITORING"/>
 *     &lt;enumeration value="SPECIFIC_REQUIREMENTS"/>
 *     &lt;enumeration value="CAUTION"/>
 *     &lt;enumeration value="TEMPORARY_RESTRICTIONS"/>
 *     &lt;enumeration value="NOT_MEET_REQUIREMENTS"/>
 *     &lt;enumeration value="EXCLUDED"/>
 *     &lt;enumeration value="NO_OFFICIAL_ADMITTANCE"/>
 *     &lt;enumeration value="PENDING_ADMITTANCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ApprovalStatusTypeContentType", namespace = "http://api.vetrf.ru/schema/cdm/codelist/v2")
@XmlEnum
public enum ApprovalStatusTypeContentType {


    /**
     * ����������� ������
     * 
     */
    UNKNOWN,

    /**
     * ������ �� ���������
     * 
     */
    UNDEFINED,

    /**
     * ��� �����������
     * 
     */
    WITHOUT_RESTRICTION,

    /**
     * ��������� ������������ ��������
     * 
     */
    ENHANCED_MONITORING,

    /**
     * ����������� ����������
     * 
     */
    SPECIFIC_REQUIREMENTS,

    /**
     * ��������������
     * 
     */
    CAUTION,

    /**
     * ��������� �����������
     * 
     */
    TEMPORARY_RESTRICTIONS,

    /**
     * �� ������������� �����������
     * 
     */
    NOT_MEET_REQUIREMENTS,

    /**
     * ���������
     * 
     */
    EXCLUDED,

    /**
     * ����������� ����������� ����� ������� ������������� ��������� ������-���������
     * 
     */
    NO_OFFICIAL_ADMITTANCE,

    /**
     * ���������� �� ��������� ����� ������� �� ������������� ��������� ������-���������
     * 
     */
    PENDING_ADMITTANCE;

    public String value() {
        return name();
    }

    public static ApprovalStatusTypeContentType fromValue(String v) {
        return valueOf(v);
    }

}
