//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.dictionary_v2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnterpriseActivityTypeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnterpriseActivityTypeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *     &lt;enumeration value="HARVESTING"/>
 *     &lt;enumeration value="PACKING"/>
 *     &lt;enumeration value="KEEPING"/>
 *     &lt;enumeration value="CUTTING"/>
 *     &lt;enumeration value="SLAUGHTER"/>
 *     &lt;enumeration value="TRADING"/>
 *     &lt;enumeration value="PROCESSING"/>
 *     &lt;enumeration value="PRODUCING"/>
 *     &lt;enumeration value="MANUFACTURING"/>
 *     &lt;enumeration value="BREEDING"/>
 *     &lt;enumeration value="TRANSFERRING"/>
 *     &lt;enumeration value="STORING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnterpriseActivityTypeContentType", namespace = "http://api.vetrf.ru/schema/cdm/codelist/v2")
@XmlEnum
public enum EnterpriseActivityTypeContentType {


    /**
     * ����������� ���
     * 
     */
    UNKNOWN,

    /**
     * ��� ������������ �� ���������
     * 
     */
    UNDEFINED,

    /**
     * ���������
     * 
     */
    HARVESTING,

    /**
     * �������
     * 
     */
    PACKING,

    /**
     * ����������
     * 
     */
    KEEPING,

    /**
     * ��������
     * 
     */
    CUTTING,

    /**
     * ����
     * 
     */
    SLAUGHTER,

    /**
     * ����������
     * 
     */
    TRADING,

    /**
     * �����������
     * 
     */
    PROCESSING,

    /**
     * �����������
     * 
     */
    PRODUCING,

    /**
     * ������������
     * 
     */
    MANUFACTURING,

    /**
     * ����������
     * 
     */
    BREEDING,

    /**
     * �����������
     * 
     */
    TRANSFERRING,

    /**
     * ��������
     * 
     */
    STORING;

    public String value() {
        return name();
    }

    public static EnterpriseActivityTypeContentType fromValue(String v) {
        return valueOf(v);
    }

}
