//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.30 at 05:14:34 PM MSK 
//


package org.example.filesFromXSD.dictionary_v2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ���������� �����������.
 * 
 * <p>Java class for ProducerAuthentication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProducerAuthentication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="certifiedActivity" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}CertifiedActivity" minOccurs="0"/>
 *         &lt;element name="certificationZone" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}CertificationZone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="status" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}ApprovalStatusType" minOccurs="0"/>
 *         &lt;element name="approvalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="approvalDocument" type="{http://api.vetrf.ru/schema/cdm/dictionary/v2}ApprovalStatement" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProducerAuthentication", propOrder = {
    "certifiedActivity",
    "certificationZone",
    "status",
    "approvalDate",
    "approvalDocument"
})
public class ProducerAuthentication {

    protected CertifiedActivity certifiedActivity;
    protected List<CertificationZone> certificationZone;
    protected ApprovalStatusType status;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar approvalDate;
    protected ApprovalStatement approvalDocument;

    /**
     * Gets the value of the certifiedActivity property.
     * 
     * @return
     *     possible object is
     *     {@link CertifiedActivity }
     *     
     */
    public CertifiedActivity getCertifiedActivity() {
        return certifiedActivity;
    }

    /**
     * Sets the value of the certifiedActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertifiedActivity }
     *     
     */
    public void setCertifiedActivity(CertifiedActivity value) {
        this.certifiedActivity = value;
    }

    /**
     * Gets the value of the certificationZone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certificationZone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertificationZone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertificationZone }
     * 
     * 
     */
    public List<CertificationZone> getCertificationZone() {
        if (certificationZone == null) {
            certificationZone = new ArrayList<CertificationZone>();
        }
        return this.certificationZone;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalStatusType }
     *     
     */
    public ApprovalStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalStatusType }
     *     
     */
    public void setStatus(ApprovalStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApprovalDate() {
        return approvalDate;
    }

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApprovalDate(XMLGregorianCalendar value) {
        this.approvalDate = value;
    }

    /**
     * Gets the value of the approvalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalStatement }
     *     
     */
    public ApprovalStatement getApprovalDocument() {
        return approvalDocument;
    }

    /**
     * Sets the value of the approvalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalStatement }
     *     
     */
    public void setApprovalDocument(ApprovalStatement value) {
        this.approvalDocument = value;
    }

}
